variables de entorno prod

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -29,6 +29,10 @@ jobs:
         ./scripts/setup-project-linux.sh prod
         sed -i 's/{{DB_USERNAME}}/'"$DB_USERNAME"'/g' .env
         sed -i 's/{{DB_PASSWD}}/'"$DB_PASSWD"'/g' .env
+        sed -i 's/{{DB_HOST}}/'"$DB_HOST"'/g' .env
+        sed -i 's/{{DB_PORT}}/'"$DB_PORT"'/g' .env
+        sed -i 's/{{DB_NAME}}/'"$DB_NAME"'/g' .env
+        sed -i 's/{{BASE_URL}}/'"$BASE_URL"'/g' .env
     - name: Build
       run: go build -v ./cmd/api
     - name: set up ssh
@@ -44,4 +48,14 @@ jobs:
         scp -i ~/.ssh/id_rsa api ubuntu@149.130.182.145:/home/ubuntu/linker-prod/url-shortener
         scp -i ~/.ssh/id_rsa .env ubuntu@149.130.182.145:/home/ubuntu/linker-prod/.env
         echo "archivos enviados"
-        ssh -i ~/.ssh/id_rsa ubuntu@149.130.182.145 'nohup ~/linker-prod/url-shortener > ~/linker-prod/url-shortener.log 2>&1 &'
+        ssh -i ~/.ssh/id_rsa ubuntu@149.130.182.145 'cd ~/linker-prod && nohup ./url-shortener > ./url-shortener.log 2>&1 &'
+    - name: E2E Tests
+      run: |
+        BASE_URL=$(grep -oP '(?<=BASE_URL=).*' .env)
+        echo "BASE_URL: $BASE_URL"
+        response=$(curl -s "${BASE_URL%/}/ping")
+        if [ "$response" != '"pong"' ]; then
+          echo "Validation failed: expected 'pong' but got '$response'"
+          exit 1
+        fi
+        echo "Validation succeeded: received 'pong'"
