curl E2E test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,15 +26,26 @@ jobs:
         ./scripts/setup-project-linux.sh prod
         sed -i 's/{{DB_USERNAME}}/'"$DB_USERNAME"'/g' .env
         sed -i 's/{{DB_PASSWD}}/'"$DB_PASSWD"'/g' .env
-    - name: Transfer files via SCP to prod
+    - name: set up ssh
       run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY_JP }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan -H 149.130.163.38 >> ~/.ssh/known_hosts
+    - name: Transfer files via SCP to prod
+      run: |
         scp -i ~/.ssh/id_rsa ./scripts/kill-current-process.sh ubuntu@149.130.163.38:~/scripts/kill-current-process.sh
         ssh -i ~/.ssh/id_rsa ubuntu@149.130.163.38 'chmod +x ~/scripts/kill-current-process.sh && ~/scripts/kill-current-process.sh && mkdir -p linker-prod'
         scp -i ~/.ssh/id_rsa api ubuntu@149.130.163.38:/home/ubuntu/linker-prod/url-shortener
         scp -i ~/.ssh/id_rsa .env ubuntu@149.130.163.38:/home/ubuntu/linker-prod/.env
         echo "archivos enviados"
         ssh -i ~/.ssh/id_rsa ubuntu@149.130.163.38 'nohup ~/linker-prod/url-shortener > ~/linker-prod/url-shortener.log 2>&1 &'
+    - name: E2E Tests
+      run: |
+        BASE_URL=$(grep -oP '(?<=BASE_URL=).*' .env)
+        response=$(curl -s "${BASE_URL%/}/ping")
+        if [ "$response" != "pong" ]; then
+          echo "Validation failed: expected 'pong' but got '$response'"
+          exit 1
+        fi
+        echo "Validation succeeded: received 'pong'"
diff --git a/.github/workflows/qualitycode.yml b/.github/workflows/qualitycode.yml
--- a/.github/workflows/qualitycode.yml
+++ b/.github/workflows/qualitycode.yml
@@ -73,16 +73,28 @@ jobs:
       uses: actions/download-artifact@v3
       with:
         name: compiled
-        path: .
-    - name: Transfer files via SCP
+        path: . 
+    - name: Set up SSH
       run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_PRIVATE_KEY_JP }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan -H 149.130.183.133 >> ~/.ssh/known_hosts
+    - name: Transfer files via SCP
+      run: |
         scp -i ~/.ssh/id_rsa ./scripts/kill-current-process.sh ubuntu@149.130.183.133:~/scripts/kill-current-process.sh
         ssh -i ~/.ssh/id_rsa ubuntu@149.130.183.133 'chmod +x ~/scripts/kill-current-process.sh && ~/scripts/kill-current-process.sh && mkdir -p linker'
         scp -i ~/.ssh/id_rsa api ubuntu@149.130.183.133:/home/ubuntu/linker/url-shortener
         scp -i ~/.ssh/id_rsa .env ubuntu@149.130.183.133:/home/ubuntu/linker/.env
         echo "archivos enviados"
         ssh -i ~/.ssh/id_rsa ubuntu@149.130.183.133 'nohup ~/linker/url-shortener > ~/linker/url-shortener.log 2>&1 &'
+    - name: E2E Tests
+      run: |
+        ssh -i ~/.ssh/id_rsa -N -L 8080:localhost:8080 ubuntu@149.130.183.133 -vvv &
+        sleep 5 # Give SSH tunnel some time to establish
+        response=$(curl -s localhost:8080/ping)
+        if [ "$response" != "pong" ]; then
+          echo "Validation failed: expected 'pong' but got '$response'"
+          exit 1
+        fi
+        echo "Validation succeeded: received 'pong'"
